"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'es' | 'fr' | 'de' | 'ur'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'navbar.admin': 'Admin',
    'navbar.toggleTheme': 'Toggle theme',
    'projects.title': 'Projects',
    'projects.description': 'Check out my latest work',
    'projects.viewAll': 'View All Projects',
    'projects.filterAll': 'All',
    'projects.filterFeatured': 'Featured',
    'projects.filterWeb': 'Web',
    'projects.filterMobile': 'Mobile',
    'projects.filterDesign': 'Design',
    'projects.noProjects': 'No projects found',
    'projects.loading': 'Loading projects...',
    'blog.title': 'Blog',
    'blog.description': 'Read my thoughts and ideas',
    'blog.viewAll': 'View All Posts',
    'blog.filterAll': 'All',
    'blog.filterTech': 'Technology',
    'blog.filterDesign': 'Design',
    'blog.filterLife': 'Life',
    'blog.noPosts': 'No blog posts found',
    'blog.loading': 'Loading posts...',
    'blog.readMore': 'Read More',
    'blog.publishedOn': 'Published on',
    'contact.title': 'Contact',
    'contact.description': 'Get in touch with me',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.error': 'Failed to send message',
    'messages.title': 'All Messages & Replies',
    'messages.description': 'Complete history of submitted messages and responses',
    'messages.loading': 'Loading messages...',
    'messages.noMessages': 'No messages yet',
    'messages.noMessagesDesc': 'Submitted messages will appear here',
    'messages.showingCount': 'Showing {count} message(s)',
    'messages.reply': 'Reply',
    'messages.typeReply': 'Type your reply...',
    'messages.sendReply': 'Reply',
    'messages.cancel': 'Cancel',
    'messages.admin': 'Admin',
    'messages.you': 'You',
    'messages.sentOn': 'Sent on',
    'messages.replyError': 'Failed to add reply. Please try again.',
    'about.title': 'About',
    'about.description': 'Learn more about me',
    'about.skills': 'Skills',
    'about.experience': 'Experience',
    'about.education': 'Education',
    'hero.title': 'Full Stack Developer',
    'hero.subtitle': 'Building modern web applications with cutting-edge technologies',
    'hero.cta': 'View Projects',
    'hero.contact': 'Contact Me',
    'hero.description': 'Passionate about creating beautiful, functional, and user-centered digital experiences. With expertise in modern web technologies, I bring ideas to life through clean code and thoughtful design.',
    'hero.roles': 'Full Stack Developer,UI/UX Designer,Problem Solver',
    'help.title': 'Help & Support',
    'help.description': 'Find answers to common questions, get support, and get in touch',
    'help.emailSupport': 'Email Support',
    'help.liveChat': 'Live Chat',
    'help.documentation': 'Documentation',
    'help.faq': 'Frequently Asked Questions',
    'help.faq.getStarted': 'How do I get started with the portfolio?',
    'help.faq.getStartedAns': 'Simply navigate through the sections using the sidebar menu. Each section showcases different aspects of my work and skills.',
    'help.faq.collaborate': 'Can I contact you for project collaborations?',
    'help.faq.collaborateAns': 'Absolutely! Use the contact form or the provided email address to reach out for collaborations and opportunities.',
    'help.faq.technologies': 'What technologies do you specialize in?',
    'help.faq.technologiesAns': 'I specialize in modern web technologies including React, Next.js, TypeScript, Node.js, and various database systems.',
    'help.faq.stayUpdated': 'How can I stay updated with your latest work?',
    'help.faq.stayUpdatedAns': 'Follow me on social media platforms and check the blog section regularly for updates and new projects.',
    'footer.copyright': '© 2024 Mohsin Raza. All rights reserved.',
    'footer.madeWith': 'Made with ❤️ and lots of ☕',
  },
  es: {
    'navbar.admin': 'Admin',
    'navbar.toggleTheme': 'Cambiar tema',
    'projects.title': 'Proyectos',
    'projects.description': 'Mira mi trabajo reciente',
    'projects.viewAll': 'Ver Todos los Proyectos',
    'projects.filterAll': 'Todos',
    'projects.filterFeatured': 'Destacados',
    'projects.filterWeb': 'Web',
    'projects.filterMobile': 'Móvil',
    'projects.filterDesign': 'Diseño',
    'projects.noProjects': 'No se encontraron proyectos',
    'projects.loading': 'Cargando proyectos...',
    'blog.title': 'Blog',
    'blog.description': 'Lee mis pensamientos e ideas',
    'blog.viewAll': 'Ver Todas las Publicaciones',
    'blog.filterAll': 'Todos',
    'blog.filterTech': 'Tecnología',
    'blog.filterDesign': 'Diseño',
    'blog.filterLife': 'Vida',
    'blog.noPosts': 'No se encontraron publicaciones',
    'blog.loading': 'Cargando publicaciones...',
    'blog.readMore': 'Leer Más',
    'blog.publishedOn': 'Publicado el',
    'contact.title': 'Contacto',
    'contact.description': 'Ponte en contacto conmigo',
    'contact.form.name': 'Tu Nombre',
    'contact.form.email': 'Tu Correo',
    'contact.form.message': 'Tu Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado exitosamente!',
    'contact.form.error': 'Error al enviar mensaje',
    'messages.title': 'Todos los Mensajes y Respuestas',
    'messages.description': 'Historial completo de mensajes enviados y respuestas',
    'messages.loading': 'Cargando mensajes...',
    'messages.noMessages': 'No hay mensajes aún',
    'messages.noMessagesDesc': 'Los mensajes enviados aparecerán aquí',
    'messages.showingCount': 'Mostrando {count} mensaje(s)',
    'messages.reply': 'Responder',
    'messages.typeReply': 'Escribe tu respuesta...',
    'messages.sendReply': 'Responder',
    'messages.cancel': 'Cancelar',
    'messages.admin': 'Admin',
    'messages.you': 'Tú',
    'messages.sentOn': 'Enviado el',
    'messages.replyError': 'Error al agregar respuesta. Inténtalo de nuevo.',
    'about.title': 'Acerca de',
    'about.description': 'Conóceme mejor',
    'about.skills': 'Habilidades',
    'about.experience': 'Experiencia',
    'about.education': 'Educación',
    'hero.title': 'Desarrollador Full Stack',
    'hero.subtitle': 'Construyendo aplicaciones web modernas con tecnologías de vanguardia',
    'hero.cta': 'Ver Proyectos',
    'hero.contact': 'Contactar',
    'hero.description': 'Apasionado por crear experiencias digitales hermosas, funcionales y centradas en el usuario. Con experiencia en tecnologías web modernas, doy vida a las ideas a través de código limpio y diseño cuidadoso.',
    'hero.roles': 'Desarrollador Full Stack,Diseñador UI/UX,Resuelve Problemas',
    'help.title': 'Ayuda y Soporte',
    'help.description': 'Encuentra respuestas a preguntas comunes, obtén soporte y ponte en contacto',
    'help.emailSupport': 'Soporte por Correo',
    'help.liveChat': 'Chat en Vivo',
    'help.documentation': 'Documentación',
    'help.faq': 'Preguntas Frecuentes',
    'help.faq.getStarted': '¿Cómo empiezo con el portafolio?',
    'help.faq.getStartedAns': 'Simplemente navega a través de las secciones usando el menú lateral. Cada sección muestra diferentes aspectos de mi trabajo y habilidades.',
    'help.faq.collaborate': '¿Puedo contactarte para colaboraciones de proyectos?',
    'help.faq.collaborateAns': '¡Absolutamente! Usa el formulario de contacto o el correo proporcionado para contactarme para colaboraciones y oportunidades.',
    'help.faq.technologies': '¿En qué tecnologías te especializas?',
    'help.faq.technologiesAns': 'Me especializo en tecnologías web modernas incluyendo React, Next.js, TypeScript, Node.js y varios sistemas de bases de datos.',
    'help.faq.stayUpdated': '¿Cómo puedo mantenerme actualizado con tu último trabajo?',
    'help.faq.stayUpdatedAns': 'Sígueme en plataformas de redes sociales y revisa la sección de blog regularmente para actualizaciones y nuevos proyectos.',
    'footer.copyright': '© 2024 Mohsin Raza. Todos los derechos reservados.',
    'footer.madeWith': 'Hecho con ❤️ y mucho ☕',
  },
  fr: {
    'navbar.admin': 'Admin',
    'navbar.toggleTheme': 'Changer le thème',
    'projects.title': 'Projets',
    'projects.description': 'Découvrez mes travaux récents',
    'projects.viewAll': 'Voir Tous les Projets',
    'projects.filterAll': 'Tous',
    'projects.filterFeatured': 'En Vedette',
    'projects.filterWeb': 'Web',
    'projects.filterMobile': 'Mobile',
    'projects.filterDesign': 'Design',
    'projects.noProjects': 'Aucun projet trouvé',
    'projects.loading': 'Chargement des projets...',
    'blog.title': 'Blog',
    'blog.description': 'Lisez mes pensées et idées',
    'blog.viewAll': 'Voir Tous les Articles',
    'blog.filterAll': 'Tous',
    'blog.filterTech': 'Technologie',
    'blog.filterDesign': 'Design',
    'blog.filterLife': 'Vie',
    'blog.noPosts': 'Aucun article trouvé',
    'blog.loading': 'Chargement des articles...',
    'blog.readMore': 'Lire Plus',
    'blog.publishedOn': 'Publié le',
    'contact.title': 'Contact',
    'contact.description': 'Contactez-moi',
    'contact.form.name': 'Votre Nom',
    'contact.form.email': 'Votre Email',
    'contact.form.message': 'Votre Message',
    'contact.form.submit': 'Envoyer le Message',
    'contact.form.sending': 'Envoi...',
    'contact.form.success': 'Message envoyé avec succès!',
    'contact.form.error': 'Erreur lors de l\'envoi du message',
    'messages.title': 'Tous les Messages et Réponses',
    'messages.description': 'Historique complet des messages envoyés et des réponses',
    'messages.loading': 'Chargement des messages...',
    'messages.noMessages': 'Aucun message encore',
    'messages.noMessagesDesc': 'Les messages envoyés apparaîtront ici',
    'messages.showingCount': 'Affichage de {count} message(s)',
    'messages.reply': 'Répondre',
    'messages.typeReply': 'Tapez votre réponse...',
    'messages.sendReply': 'Répondre',
    'messages.cancel': 'Annuler',
    'messages.admin': 'Admin',
    'messages.you': 'Vous',
    'messages.sentOn': 'Envoyé le',
    'messages.replyError': 'Erreur lors de l\'ajout de la réponse. Réessayez.',
    'about.title': 'À propos',
    'about.description': 'Apprenez-en plus sur moi',
    'about.skills': 'Compétences',
    'about.experience': 'Expérience',
    'about.education': 'Éducation',
    'hero.title': 'Développeur Full Stack',
    'hero.subtitle': 'Construire des applications web modernes avec des technologies de pointe',
    'hero.cta': 'Voir Projets',
    'hero.contact': 'Me Contacter',
    'hero.description': 'Passionné par la création d\'expériences numériques belles, fonctionnelles et centrées sur l\'utilisateur. Avec une expertise dans les technologies web modernes, je donne vie aux idées grâce à un code propre et une design réfléchi.',
    'hero.roles': 'Développeur Full Stack,Designer UI/UX,Résolveur de Problèmes',
    'help.title': 'Aide et Support',
    'help.description': 'Trouvez des réponses aux questions fréquentes, obtenez du support et contactez-nous',
    'help.emailSupport': 'Support Email',
    'help.liveChat': 'Chat en Direct',
    'help.documentation': 'Documentation',
    'help.faq': 'Questions Fréquentes',
    'help.faq.getStarted': 'Comment commencer avec le portfolio?',
    'help.faq.getStartedAns': 'Naviguez simplement à travers les sections en utilisant le menu latéral. Chaque section présente différents aspects de mon travail et de mes compétences.',
    'help.faq.collaborate': 'Puis-je vous contacter pour des collaborations de projets?',
    'help.faq.collaborateAns': 'Absolument! Utilisez le formulaire de contact ou l\'email fourni pour me contacter pour des collaborations et opportunités.',
    'help.faq.technologies': 'Dans quelles technologies vous spécialisez-vous?',
    'help.faq.technologiesAns': 'Je me spécialise dans les technologies web modernes incluant React, Next.js, TypeScript, Node.js et divers systèmes de bases de données.',
    'help.faq.stayUpdated': 'Comment puis-je rester informé de votre dernier travail?',
    'help.faq.stayUpdatedAns': 'Suivez-moi sur les plateformes de médias sociaux et consultez la section blog régulièrement pour les mises à jour et nouveaux projets.',
    'footer.copyright': '© 2024 Mohsin Raza. Tous droits réservés.',
    'footer.madeWith': 'Fait avec ❤️ et beaucoup de ☕',
  },
  de: {
    'navbar.admin': 'Admin',
    'navbar.toggleTheme': 'Design wechseln',
    'projects.title': 'Projekte',
    'projects.description': 'Meine neuesten Arbeiten ansehen',
    'projects.viewAll': 'Alle Projekte Ansehen',
    'projects.filterAll': 'Alle',
    'projects.filterFeatured': 'Vorgestellt',
    'projects.filterWeb': 'Web',
    'projects.filterMobile': 'Mobil',
    'projects.filterDesign': 'Design',
    'projects.noProjects': 'Keine Projekte gefunden',
    'projects.loading': 'Lade Projekte...',
    'blog.title': 'Blog',
    'blog.description': 'Meine Gedanken und Ideen lesen',
    'blog.viewAll': 'Alle Beiträge Ansehen',
    'blog.filterAll': 'Alle',
    'blog.filterTech': 'Technologie',
    'blog.filterDesign': 'Design',
    'blog.filterLife': 'Leben',
    'blog.noPosts': 'Keine Beiträge gefunden',
    'blog.loading': 'Lade Beiträge...',
    'blog.readMore': 'Mehr Lesen',
    'blog.publishedOn': 'Veröffentlicht am',
    'contact.title': 'Kontakt',
    'contact.description': 'Nehmen Sie Kontakt mit mir auf',
    'contact.form.name': 'Ihr Name',
    'contact.form.email': 'Ihre E-Mail',
    'contact.form.message': 'Ihre Nachricht',
    'contact.form.submit': 'Nachricht Senden',
    'contact.form.sending': 'Sende...',
    'contact.form.success': 'Nachricht erfolgreich gesendet!',
    'contact.form.error': 'Fehler beim Senden der Nachricht',
    'messages.title': 'Alle Nachrichten & Antworten',
    'messages.description': 'Vollständiger Verlauf gesendeter Nachrichten und Antworten',
    'messages.loading': 'Lade Nachrichten...',
    'messages.noMessages': 'Noch keine Nachrichten',
    'messages.noMessagesDesc': 'Gesendete Nachrichten erscheinen hier',
    'messages.showingCount': 'Zeige {count} Nachricht(en)',
    'messages.reply': 'Antworten',
    'messages.typeReply': 'Tippe deine Antwort...',
    'messages.sendReply': 'Antworten',
    'messages.cancel': 'Abbrechen',
    'messages.admin': 'Admin',
    'messages.you': 'Du',
    'messages.sentOn': 'Gesendet am',
    'messages.replyError': 'Fehler beim Hinzufügen der Antwort. Versuche es erneut.',
    'about.title': 'Über',
    'about.description': 'Erfahren Sie mehr über mich',
    'about.skills': 'Fähigkeiten',
    'about.experience': 'Erfahrung',
    'about.education': 'Ausbildung',
    'hero.title': 'Full Stack Entwickler',
    'hero.subtitle': 'Moderne Webanwendungen mit cutting-edge Technologien entwickeln',
    'hero.cta': 'Projekte Ansehen',
    'hero.contact': 'Kontaktieren',
    'hero.description': 'Leidenschaftlich darin, schöne, funktionale und benutzerzentrierte digitale Erlebnisse zu schaffen. Mit Expertise in modernen Web-Technologien bringe ich Ideen durch sauberen Code und durchdachtes Design zum Leben.',
    'hero.roles': 'Full Stack Entwickler,UI/UX Designer,Problemlöser',
    'help.title': 'Hilfe & Support',
    'help.description': 'Finden Sie Antworten auf häufige Fragen, erhalten Sie Support und kontaktieren Sie uns',
    'help.emailSupport': 'E-Mail Support',
    'help.liveChat': 'Live Chat',
    'help.documentation': 'Dokumentation',
    'help.faq': 'Häufig Gestellte Fragen',
    'help.faq.getStarted': 'Wie fange ich mit dem Portfolio an?',
    'help.faq.getStartedAns': 'Navigieren Sie einfach durch die Abschnitte mit dem seitlichen Menü. Jeder Abschnitt zeigt verschiedene Aspekte meiner Arbeit und Fähigkeiten.',
    'help.faq.collaborate': 'Kann ich Sie für Projektkollaborationen kontaktieren?',
    'help.faq.collaborateAns': 'Absolut! Verwenden Sie das Kontaktformular oder die bereitgestellte E-Mail, um mich für Kollaborationen und Möglichkeiten zu kontaktieren.',
    'help.faq.technologies': 'In welchen Technologien sind Sie spezialisiert?',
    'help.faq.technologiesAns': 'Ich bin spezialisiert auf moderne Web-Technologien einschließlich React, Next.js, TypeScript, Node.js und verschiedene Datenbanksysteme.',
    'help.faq.stayUpdated': 'Wie kann ich über Ihre neueste Arbeit auf dem Laufenden bleiben?',
    'help.faq.stayUpdatedAns': 'Folgen Sie mir auf Social-Media-Plattformen und überprüfen Sie regelmäßig den Blog-Bereich für Updates und neue Projekte.',
    'footer.copyright': '© 2024 Mohsin Raza. Alle Rechte vorbehalten.',
    'footer.madeWith': 'Gemacht mit ❤️ und viel ☕',
  },
  ur: {
    'navbar.admin': 'ایڈمن',
    'navbar.toggleTheme': 'تھیم تبدیل کریں',
    'projects.title': 'پروجیکٹس',
    'projects.description': 'میری تازہ کار دیکھیں',
    'projects.viewAll': 'تمام پروجیکٹس دیکھیں',
    'projects.filterAll': 'تمام',
    'projects.filterFeatured': 'نمایاں گیا',
    'projects.filterWeb': 'ویب',
    'projects.filterMobile': 'موبائل',
    'projects.filterDesign': 'ڈیزائن',
    'projects.noProjects': 'کوئی پروجیکٹ نہیں ملا',
    'projects.loading': 'پروجیکٹس لوڈ ہو رہے ہیں...',
    'blog.title': 'بلاگ',
    'blog.description': 'میرے خیالات اور خیالات پڑھیں',
    'blog.viewAll': 'تمام پوسٹس دیکھیں',
    'blog.filterAll': 'تمام',
    'blog.filterTech': 'ٹیکنالوجی',
    'blog.filterDesign': 'ڈیزائن',
    'blog.filterLife': 'زندگی',
    'blog.noPosts': 'کوئی بلاگ پوسٹ نہیں ملا',
    'blog.loading': 'پوسٹس لوڈ ہو رہے ہیں...',
    'blog.readMore': 'مزید پڑھیں',
    'blog.publishedOn': 'شائع کیا گیا',
    'contact.title': 'رابطہ',
    'contact.description': 'میرے سے رابطہ کریں',
    'contact.form.name': 'آپ کا نام',
    'contact.form.email': 'آپ کا ای میل',
    'contact.form.message': 'آپا پیغام',
    'contact.form.submit': 'پیغام بھیجیں',
    'contact.form.sending': 'بھیجا جا رہا ہے...',
    'contact.form.success': 'پیغام کامیابی سے بھیج دیا گیا!',
    'contact.form.error': 'پیغام بھیجنے میں ناکام',
    'messages.title': 'تمام پیغامات اور جوابات',
    'messages.description': 'بھیجے گئے پیغامات اور جوابات کا مکمل تاریخ',
    'messages.loading': 'پیغامات لوڈ ہو رہے ہیں...',
    'messages.noMessages': 'ابھی تک کوئی پیغام نہیں',
    'messages.noMessagesDesc': 'بھیجے گئے پیغامات یہاں ظاہر ہوں گے',
    'messages.showingCount': '{count} پیغام(ات) دکھا رہے ہیں',
    'messages.reply': 'جواب دیں',
    'messages.typeReply': 'اپنا جواب ٹائپ کریں...',
    'messages.sendReply': 'جواب دیں',
    'messages.cancel': 'منسوخ کریں',
    'messages.admin': 'ایڈمن',
    'messages.you': 'آپ',
    'messages.sentOn': 'بھیجا گیا',
    'messages.replyError': 'جواب شامل کرنے میں ناکام۔ دوبارہ کوشش کریں۔',
    'about.title': 'کے بارے میں',
    'about.description': 'میرے بارے میں زیادہ جانیں',
    'about.skills': 'مہارت',
    'about.experience': 'تجربہ',
    'about.education': 'تعلیم',
    'hero.title': 'فول اسٹیک ڈویلپر',
    'hero.subtitle': 'جدید ٹیکنالوجیز کے ساتھ جدید ویب ایپلیکیشنز بنانا',
    'hero.cta': 'پروجیکٹس دیکھیں',
    'hero.contact': 'رابطہ کریں',
    'hero.description': 'خوبصورت، کارکرد اور صارف مرکزی ڈیجیٹل تجربات بنانے کے لیے پرجوش۔ جدید ویب ٹیکنالوجیز میں مہارت کے ساتھ، میں صاف کوڈ اور سوچے ہوئے ڈیزائن کے ذریعے خیالات کو زندگی دیتا ہوں۔',
    'hero.roles': 'فول اسٹیک ڈویلپر,UI/UX ڈیزائنر,مسئلہ حل کرنے والا',
    'help.title': 'مدد اور سپورٹ',
    'help.description': 'عمومی سوالات کے جوابات تلاش کریں، مدد حاصل کریں اور رابطہ کریں',
    'help.emailSupport': 'ای میل سپورٹ',
    'help.liveChat': 'لائیو چیٹ',
    'help.documentation': 'دستاویزات',
    'help.faq': 'اکثر پوچھے گئے سوالات',
    'help.faq.getStarted': 'میں پورٹ فولیو سے کیسے شروع کروں؟',
    'help.faq.getStartedAns': 'بس سائیڈ بار مینیو کا استعمال کرتے ہوئے حصوں میں نیویگیٹ کریں۔ ہر سیکشن میرے کام اور مہارت کے مختلف پہلوؤں کو دکھاتا ہے۔',
    'help.faq.collaborate': 'کیا میں آپ سے پروجیکٹ تعاون کے لیے رابطہ کر سکتا ہوں؟',
    'help.faq.collaborateAns': 'بالکل! تعاون اور مواقع کے لیے رابطہ فارم یا فراہم کردہ ای میل کا استعمال کرکے مجھ سے رابطہ کریں۔',
    'help.faq.technologies': 'آپ کون سی ٹیکنالوجیز میں ماہر رکھتے ہیں؟',
    'help.faq.technologiesAns': 'میں جدید ویب ٹیکنالوجیز میں ماہر رکھتا ہوں جیسے ری ایکٹ، نیکسٹ جے ایس، ٹائپ اسکرپٹ، نوڈ جے ایس اور مختلف ڈیٹا بیس سسٹمز۔',
    'help.faq.stayUpdated': 'میں آپ کے تازہ کام سے آگاہ کیسے رہ سکتا ہوں؟',
    'help.faq.stayUpdatedAns': 'سوشل میڈیا پلیٹ فارمز پر مجھے فالو کریں اور اپ ڈیٹس اور نئے پروجیکٹس کے لیے باقاعدگی سے بلاگ سیکشن چیک کریں۔',
    'footer.copyright': '© 2024 محسن رضا۔ تمام حقوق محفوظ ہیں۔',
    'footer.madeWith': '❤️ اور بہت سے ☕ کے ساتھ بنایا گیا',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    // Load saved language preference from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && ['en', 'es', 'fr', 'de', 'ur'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    } else {
      // Detect browser language
      const browserLanguage = navigator.language.split('-')[0] as Language
      if (['en', 'es', 'fr', 'de', 'ur'].includes(browserLanguage)) {
        setLanguage(browserLanguage)
      }
    }
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
